on: push
name: Cargo test

jobs:
    test_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run cargo test
              run: cargo test --frozen
